### ISSUE TITLE
碰到这个问题不懂怎么解决   大神指条明路 

### ISSUE THREAD

**Issue by Rdxer** [gpfduoduo/WiFiDetective#2]
22:25:59 Gradle sync failed: D:\developtools\gradle\gradle-2.10-all.zip (系统找不到指定的路径。)
         Consult IDE log for more details (Help | Show Log)

**Comment by 54lazycat** [comment]
@Rdxer 那个包是在他的电脑的路径。你可以注释掉，再反注释上一行代码

**Comment by Rdxer** [comment]
谢谢大佬
